### ISSUE TITLE
Introduce python dependency management

### ISSUE THREAD

**Issue by theycallmejeano** [Kinjuriu/my_recommendation_system#1]
## Description
Python can grab libraries from anywhere on the OS. A python virtual environment isolates the packages required for a specific repository(sometimes stored in a `requirements.txt` file)

Read - https://realpython.com/python-virtual-environments-a-primer/
There are different dependency management tools; pipenv, virutalenv, poetry. They are well explained in this post 
https://medium.com/dsckiit/managing-dependencies-in-python-a580ded4f67

Pipenv can work, but I suggest you introduce a poetry environment to this repo, as it has the fewest dependency management issues.

## Acceptance Criteria
The dependencies in here are managed from a dependency management tool
![image](https://user-images.githubusercontent.com/51367771/202410086-f3155e12-b883-4726-8e7f-eace003ad894.png)

If using a Pipenv environment, we should have a `Pipfile` and`Pipfile.lock` with the dependencies
If using a Poetry environment, we should have a `pyproject.toml` and `poetry.lock` with the dependencies

**Comment by Kinjuriu** [comment]
Well received, thank you.

**Comment by Kinjuriu** [comment]
Thank you, this is now fixed by [PR 11](https://github.com/Kinjuriu/my_recommendation_system/pull/11)
