### ISSUE TITLE
Structure repository

### ISSUE THREAD

**Issue by theycallmejeano** [Kinjuriu/my_recommendation_system#2]
## Description
To prepare this repo for a possible package deployment, we should use a bootstraping method. e.g. Pyscaffold https://pypi.org/project/PyScaffold/. 
This will introduce a series of files and folders for package management
Although the bare minimum we would need is an `src` folder, its still good to practice scaffolding

## Acceptance criteria
The repo should now include a `src` folder, either manually created or from pyscaffold.
The notebook should still be intact

NB. @Kinjuriu start with this issue, then do the environment management

**Comment by Kinjuriu** [comment]
Noted with thanks.

**Comment by Kinjuriu** [comment]
Thank you, this is now fixed by [PR 10](https://github.com/Kinjuriu/my_recommendation_system/pull/10)
