### ISSUE TITLE
Create pre-processing file

### ISSUE THREAD

**Issue by theycallmejeano** [Kinjuriu/my_recommendation_system#3]
## Description
Once the repo has been re-organised and packages installed in an environment, create a script in src folder to contain the pre-processing functions

## Acceptance criteria
The pre-processing functions are defined in a script `preprocess.py` stored in src folder

**Comment by Kinjuriu** [comment]
okay.

**Comment by Kinjuriu** [comment]
Thank you, this is now fixed by [PR 12](https://github.com/Kinjuriu/my_recommendation_system/pull/12)
