### ISSUE TITLE
Create a recommender script

### ISSUE THREAD

**Issue by theycallmejeano** [Kinjuriu/my_recommendation_system#4]
## Description

Once the repo has been re-organised and packages installed in an environment, create a script in src folder to contain the recommender functions

## Acceptance criteria

The recommender functions are defined in a script `recommender.py` stored in src folder

**Comment by Kinjuriu** [comment]
Noted with thanks.

**Comment by Kinjuriu** [comment]
Thank you, this is now fixed by [PR 13](https://github.com/Kinjuriu/my_recommendation_system/pull/13)
