### ISSUE TITLE
Generate the main.py script

### ISSUE THREAD

**Issue by theycallmejeano** [Kinjuriu/my_recommendation_system#5]
## Description

Once #3 and #4 are complete, these should be added to `main.py` script, which will be used to run the pipeline and output results in a csv file

We can groom this more once we're happy with the previous issues

## Acceptance criteria

The recommender runs from a `main.py` script rather than the notebook

**Comment by Kinjuriu** [comment]
Thank you, this is now fixed by [PR 14](https://github.com/Kinjuriu/my_recommendation_system/pull/14)
